USE edukapptests;
INSERT INTO functionality (name, uri, level) values ('virtual learning environment', 'http://itec.det.uvigo.es/itec/vocabularies/Functionality#virlea', 1);
INSERT INTO functionality (name, uri, level) values ('database', 'http://itec.det.uvigo.es/itec/vocabularies/Functionality#databa', 1);
INSERT INTO functionality (name, uri, level) values ('data analysis tool', 'http://itec.det.uvigo.es/itec/vocabularies/Functionality#datana', 1);
INSERT INTO functionality (name, uri, level) values ('reference tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#reftoo', 1);
INSERT INTO functionality (name, uri, level) values ('game','http://itec.det.uvigo.es/itec/vocabularies/Functionality#game', 1);
INSERT INTO functionality (name, uri, level) values ('geotagging tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#geotoo', 1);
INSERT INTO functionality (name, uri, level) values ('instructional design tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#insdes',1);
INSERT INTO functionality (name, uri, level) values ('multi-media repository client','http://itec.det.uvigo.es/itec/vocabularies/Functionality#mulrep', 1);
INSERT INTO functionality (name, uri, level) values ('podcast client', 'http://itec.det.uvigo.es/itec/vocabularies/Functionality#podcli', 1);
INSERT INTO functionality (name, uri, level) values ('search engine', 'http://itec.det.uvigo.es/itec/vocabularies/Functionality#seaeng', 1);
INSERT INTO functionality (name, uri, level) values ('simulation software', 'http://itec.det.uvigo.es/itec/vocabularies/Functionality#simsof', 1);
INSERT INTO functionality (name, uri, level) values ('syndication feed','http://itec.det.uvigo.es/itec/vocabularies/Functionality#synfee',1);
INSERT INTO functionality (name, uri, level) values ('web browser','http://itec.det.uvigo.es/itec/vocabularies/Functionality#webbro',1);
INSERT INTO functionality (name, uri, level) values ('capture tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#captoo',1);
INSERT INTO functionality (name, uri, level) values ('projection tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#protoo',1);
INSERT INTO functionality (name, uri, level) values ('student information system','http://itec.det.uvigo.es/itec/vocabularies/Functionality#stuinf',2);
INSERT INTO functionality (name, uri, level) values ('classroom management system','http://itec.det.uvigo.es/itec/vocabularies/Functionality#claman',2);
INSERT INTO functionality (name, uri, level) values ('content management tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#conman',2);
INSERT INTO functionality (name, uri, level) values ('dictionary','http://itec.det.uvigo.es/itec/vocabularies/Functionality#dictio',2);
INSERT INTO functionality (name, uri, level) values ('encyclopedia','http://itec.det.uvigo.es/itec/vocabularies/Functionality#encycl',2);
INSERT INTO functionality (name, uri, level) values ('mapping tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#maptoo',2);
INSERT INTO functionality (name, uri, level) values ('online game','http://itec.det.uvigo.es/itec/vocabularies/Functionality#onlgam',2);
INSERT INTO functionality (name, uri, level) values ('offline game','http://itec.det.uvigo.es/itec/vocabularies/Functionality#offgam',2);
INSERT INTO functionality (name, uri, level) values ('media authoring tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#medaut',2);
INSERT INTO functionality (name, uri, level) values ('virtual world client','http://itec.det.uvigo.es/itec/vocabularies/Functionality#virwor',2);
INSERT INTO functionality (name, uri, level) values ('discrete event simulation','http://itec.det.uvigo.es/itec/vocabularies/Functionality#diseve',2);
INSERT INTO functionality (name, uri, level) values ('audio capture tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#audcap',2);
INSERT INTO functionality (name, uri, level) values ('photo capture tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#phocap',2);
INSERT INTO functionality (name, uri, level) values ('video capture tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#vidcap',2);
INSERT INTO functionality (name, uri, level) values ('scanner','http://itec.det.uvigo.es/itec/vocabularies/Functionality#scanne',2);
INSERT INTO functionality (name, uri, level) values ('QR Code reader','http://itec.det.uvigo.es/itec/vocabularies/Functionality#qrcode',2);
INSERT INTO functionality (name, uri, level) values ('activity management tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#actman',3);
INSERT INTO functionality (name, uri, level) values ('automated assessment tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#autass',3);
INSERT INTO functionality (name, uri, level) values ('grading tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#gratoo',3);
INSERT INTO functionality (name, uri, level) values ('competency management tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#comman',3);
INSERT INTO functionality (name, uri, level) values ('online portfolio tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#onlpor',3);
INSERT INTO functionality (name, uri, level) values ('student reporting tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#sturep',3);
INSERT INTO functionality (name, uri, level) values ('task management tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#tasman',3);
INSERT INTO functionality (name, uri, level) values ('collaboration tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#coltoo',3);
INSERT INTO functionality (name, uri, level) values ('communication tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#comtoo',3);
INSERT INTO functionality (name, uri, level) values ('file transfer client','http://itec.det.uvigo.es/itec/vocabularies/Functionality#filtra',3);
INSERT INTO functionality (name, uri, level) values ('online storage tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#onlsto',3);
INSERT INTO functionality (name, uri, level) values ('online multi-player game','http://itec.det.uvigo.es/itec/vocabularies/Functionality#onlmul',3);
INSERT INTO functionality (name, uri, level) values ('online single-player game','http://itec.det.uvigo.es/itec/vocabularies/Functionality#onlsin',3);
INSERT INTO functionality (name, uri, level) values ('offline multi-player game','http://itec.det.uvigo.es/itec/vocabularies/Functionality#offmul',3);
INSERT INTO functionality (name, uri, level) values ('offline single-player game','http://itec.det.uvigo.es/itec/vocabularies/Functionality#offsin',3);
INSERT INTO functionality (name, uri, level) values ('concept-mapping tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#contoo',3);
INSERT INTO functionality (name, uri, level) values ('presentation graphics tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#pregra',3);
INSERT INTO functionality (name, uri, level) values ('audio editor','http://itec.det.uvigo.es/itec/vocabularies/Functionality#audedi',3);
INSERT INTO functionality (name, uri, level) values ('image editor','http://itec.det.uvigo.es/itec/vocabularies/Functionality#imaedi',3);
INSERT INTO functionality (name, uri, level) values ('spreadsheet tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#sprtoo',3);
INSERT INTO functionality (name, uri, level) values ('video editor','http://itec.det.uvigo.es/itec/vocabularies/Functionality#webaut',3);
INSERT INTO functionality (name, uri, level) values ('web authoring tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#webaut',3);
INSERT INTO functionality (name, uri, level) values ('word processor','http://itec.det.uvigo.es/itec/vocabularies/Functionality#worpro',3);
INSERT INTO functionality (name, uri, level) values ('pdf editor','http://itec.det.uvigo.es/itec/vocabularies/Functionality#pdfedi',3);
INSERT INTO functionality (name, uri, level) values ('shared editing tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#shaedi',3);
INSERT INTO functionality (name, uri, level) values ('calendar','http://itec.det.uvigo.es/itec/vocabularies/Functionality#calend',4);
INSERT INTO functionality (name, uri, level) values ('location aware application', 'http://itec.det.uvigo.es/itec/vocabularies/Functionality#locawa',4);
INSERT INTO functionality (name, uri, level) values ('social networking tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#socnet',4);
INSERT INTO functionality (name, uri, level) values ('data sharing tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#datsha',4);
INSERT INTO functionality (name, uri, level) values ('wiki','http://itec.det.uvigo.es/itec/vocabularies/Functionality#wiki',4);
INSERT INTO functionality (name, uri, level) values ('feedback tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#feetoo',4);
INSERT INTO functionality (name, uri, level) values ('ideas sharing','http://itec.det.uvigo.es/itec/vocabularies/Functionality#idesha',4);
INSERT INTO functionality (name, uri, level) values ('team sharing','http://itec.det.uvigo.es/itec/vocabularies/Functionality#teasha',4);
INSERT INTO functionality (name, uri, level) values ('synchronous communication tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#syncom',4);
INSERT INTO functionality (name, uri, level) values ('asynchronous communication tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#asycom',4);
INSERT INTO functionality (name, uri, level) values ('social bookmarking tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#socboo',5);
INSERT INTO functionality (name, uri, level) values ('annotation tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#anntoo',5);
INSERT INTO functionality (name, uri, level) values ('tagging tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#tagtoo',5);
INSERT INTO functionality (name, uri, level) values ('rating tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#rattoo',5);
INSERT INTO functionality (name, uri, level) values ('audio sharing tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#audsha',5);
INSERT INTO functionality (name, uri, level) values ('photo sharing tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#phosha',5);
INSERT INTO functionality (name, uri, level) values ('video sharing client','http://itec.det.uvigo.es/itec/vocabularies/Functionality#vidsha',5);
INSERT INTO functionality (name, uri, level) values ('file sharing tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#filsha',5);
INSERT INTO functionality (name, uri, level) values ('voting tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#vottoo',5);
INSERT INTO functionality (name, uri, level) values ('survery tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#surtoo',5);
INSERT INTO functionality (name, uri, level) values ('peer assessing tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#peeass',5);
INSERT INTO functionality (name, uri, level) values ('group individual contribution review','http://itec.det.uvigo.es/itec/vocabularies/Functionality#groind',5);
INSERT INTO functionality (name, uri, level) values ('application sharing tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#appsha',5);
INSERT INTO functionality (name, uri, level) values ('audio conference tool','http://itec.det.uvigo.es/itec/vocabularies/Functionality#audcon',5);
INSERT INTO functionality (name, uri, level) values ('chat client','http://itec.det.uvigo.es/itec/vocabularies/Functionality#chacli',5);
INSERT INTO functionality (name, uri, level) values ('instant messaging client','http://itec.det.uvigo.es/itec/vocabularies/Functionality#insmes',5);
INSERT INTO functionality (name, uri, level) values ('phone','http://itec.det.uvigo.es/itec/vocabularies/Functionality#phone',5);
INSERT INTO functionality (name, uri, level) values ('video conferencing client','http://itec.det.uvigo.es/itec/vocabularies/Functionality#vidcon',5);
INSERT INTO functionality (name, uri, level) values ('blog','http://itec.det.uvigo.es/itec/vocabularies/Functionality#blog',5);
INSERT INTO functionality (name, uri, level) values ('bulleting board system','http://itec.det.uvigo.es/itec/vocabularies/Functionality#bulboa',5);
INSERT INTO functionality (name, uri, level) values ('forum','http://itec.det.uvigo.es/itec/vocabularies/Functionality#forum',5);
INSERT INTO functionality (name, uri, level) values ('messaging client','http://itec.det.uvigo.es/itec/vocabularies/Functionality#mescli',5);
INSERT INTO functionality (name, uri, level) values ('online journal','http://itec.det.uvigo.es/itec/vocabularies/Functionality#onljou',5);
INSERT INTO functionality (name, uri, level) values ('email','http://itec.det.uvigo.es/itec/vocabularies/Functionality#email',6);
INSERT INTO functionality (name, uri, level) values ('sms','http://itec.det.uvigo.es/itec/vocabularies/Functionality#sms',6);
INSERT INTO functionality (name, uri, level) values ('mms','http://itec.det.uvigo.es/itec/vocabularies/Functionality#mms',6);
INSERT INTO functionality (name, uri, level) values ('ubiquitous messaging','http://itec.det.uvigo.es/itec/vocabularies/Functionality#ubimes',6);